# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5433/DBOficina

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SECURITY CONFIG
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-muito-longa-e-segura-12345678901234567890}

# JAVA 21 VIRTUAL THREADS
spring.threads.virtual.enabled=true

# HIKARI POOL
spring.datasource.hikari.maximum-pool-size=10